### ISSUE TITLE
add `Moonbeam` network

### ISSUE THREAD

**Issue by YouStillAlive** [The-Poolz/PoolzReactHelper#112]
Network name: **Moonbeam**
RPC URL: https://rpc.api.moonbeam.network
Chain ID: **1284**
Currency symbol: **GLMR**
Block explorer URL: https://moonbeam.moonscan.io

## List of contracts:
**VaultManager** deployed at: 0x2Bb9cFF524C76eb2eA27bC6cDbB93447115D8dcC
Strapi: `VaultManager@v1.0.0`

**LockDealNFT** deployed at: 0x6d77B5147CDE6Fa287c1266A33e09a09651D36d0
Strapi: `LockDealNFT@1.0.4`

**DealProvider** deployed at: 0x3c845DbB07BdFdD73FbC5Df4bA47EdeA20BCa489
Strapi: `DealProvider@1.0.4`

**LockDealProvider** deployed at: 0x7521fF2baca97397C8936E35dAc225f6bc1070Cf
Strapi: `LockDealProvider@1.0.4`

**TimedDealProvider** deployed at: 0x9c8F78E0aeAB8190c9d1DF7BEd0B26c1EDcB8DE6
Strapi: `TimedDealProvider@1.0.4`

**SimpleBuilder** deployed at: 0xA2A0bEEfda596Fdb321240dD283D8cBf65b252f1
Strapi: `SimpleBuilder@1.2.2`

**Comment by DVitaliy** [comment]
@Lomet 
![Xnip2024-09-12_18-15-53](https://github.com/user-attachments/assets/5a93bdf6-9c1b-4015-89e7-def20a38764f)
 this is not corrected `VersionNumber`

![Xnip2024-09-12_18-17-12](https://github.com/user-attachments/assets/bccb38bc-a769-4279-81a1-a85d9fd1c7e0)

**Comment by Lomet** [comment]
![image](https://github.com/user-attachments/assets/ea47bb12-9936-4dad-ade3-a22650a73264)

I removed the rogue `v`
