### ISSUE TITLE
add LockDealNFT chain 43114

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/PoolzReactHelper#119]
The deployment script creates this issue.
The following contracts were deployed successfully:

- VaultManager deployed at 0x9c8F78E0aeAB8190c9d1DF7BEd0B26c1EDcB8DE6
- LockDealNFT deployed at 0xA2A0bEEfda596Fdb321240dD283D8cBf65b252f1
- DealProvider deployed at 0x65f62efEb1A43064081443791d8C10Db0A1FB511
- LockDealProvider deployed at 0x960c76BeC76ebB223B3e29B35a70c40925f38d66
- TimedDealProvider deployed at 0x2dd5B5E374B2d32152507100a42CA15f7707F504
- CollateralProvider deployed at 0x9cfd8c7834Be0DfE41F3FE68C29124066D5Cd13b
- RefundProvider deployed at 0xEE099538ED077F831cB9Af44fFD51Ec7Fd95c7DE
- SimpleBuilder deployed at 0x756CD0834C2610f583B8324934A0269E3fef6f72
- SimpleRefundBuilder deployed at 0xff1f0872f5462b30acdA92a08D2388612F7Bf7EE

chain: [Avalanche](https://www.avax.network/)
chain Id: 43114

**Comment by YouStillAlive** [comment]
**Strapi** versions:
```
VaultManager@1.0.0
```
```
LockDealNFT@1.0.4
```
```
DealProvider@1.0.4
```
```
LockDealProvider@1.0.4
```
```
TimedDealProvider@1.0.4
```
```
CollateralProvider@1.0.2
```
```
RefundProvider@1.0.2
```
```
SimpleBuilder@1.2.2
```
```
SimpleRefundBuilder@1.2.2
```
