### ISSUE TITLE
Add BNB Main net Addresss

### ISSUE THREAD

**Issue by DVitaliy** [The-Poolz/PoolzReactHelper#39]
![Xnip2023-12-18_14-07-14](https://github.com/The-Poolz/PoolzReactHelper/assets/1593183/7179325a-ade9-454f-857e-c10ad48339d8)

**Comment by ashwinarora** [comment]
Need to update BSC Testnet contracts as well

VaultManager: 0xF0A8AAc3deB7596527A61697D0a9728E3A67D3B7 
LockDealNFT: 0xe42876a77108E8B3B2af53907f5e533Cba2Ce7BE
DealProvider: 0x70B0F2fd774376063faCC9178307cF1E18Ea3aF0
LockDealProvider: 0x8FDf10F414395366b9fFbBa2058fe913D4F98cef
TimedDealProvider: 0xD3dC0C40387F19cFE2b434D56AC4CE939c789328
CollateralProvider: 0xB1fa4dBEA085d10e05483A08ba6bc43a893BA921
RefundProvider: 0xeC1AE4E0C8fF8973016282d70eFbc3bbC5A682D9
SimpleBuilder: 0x06daa28410A8e26fC86DF3c3d2Cfb2875F4887e8
SimpleRefundBuilder: 0x2A9E8f7a179D5Ddec77f87efB3D7b494E4d049f0
DelayVaultMigrator: 0xFc4E9DDd1E21a9BaDEb1A4C81687A20fe135A54F
DelayVaultProvider: 0x9fd743f499d852E3A2cFEAC037e5562126468D28

**Comment by ashwinarora** [comment]
LockDealNFT@0.9.1-ironblocks
VaultManager@0.0.4-ironblocks
DealProvider@0.9.1-ironblocks
LockDealProvider@0.9.1-ironblocks
TimedDealProvider@0.9.1-ironblocks
RefundProvider@0.9.1-ironblocks
CollateralProvider@0.9.1-ironblocks
SimpleBuilder@0.9.1-ironblocks
SimpleRefundBuilder@0.9.1-ironblocks
DelayVaultProvider@0.9.5-ironblocks
DelayVaultMigrator@0.9.1-ironblocks

**Comment by Lomet** [comment]
> Need to update BSC Testnet contracts as well
> 
> VaultManager: 0xF0A8AAc3deB7596527A61697D0a9728E3A67D3B7 LockDealNFT: 0xe42876a77108E8B3B2af53907f5e533Cba2Ce7BE DealProvider: 0x70B0F2fd774376063faCC9178307cF1E18Ea3aF0 LockDealProvider: 0x8FDf10F414395366b9fFbBa2058fe913D4F98cef TimedDealProvider: 0xD3dC0C40387F19cFE2b434D56AC4CE939c789328 CollateralProvider: 0xB1fa4dBEA085d10e05483A08ba6bc43a893BA921 RefundProvider: 0xeC1AE4E0C8fF8973016282d70eFbc3bbC5A682D9 SimpleBuilder: 0x06daa28410A8e26fC86DF3c3d2Cfb2875F4887e8 SimpleRefundBuilder: 0x2A9E8f7a179D5Ddec77f87efB3D7b494E4d049f0 DelayVaultMigrator: 0xFc4E9DDd1E21a9BaDEb1A4C81687A20fe135A54F DelayVaultProvider: 0x9fd743f499d852E3A2cFEAC037e5562126468D28

Let's do it in new PR - right now the Main is priority
